import Head from 'next/head'
import Hero from '../components/Hero'
import Slider from '../components/Slider'
import  { SliderData } from '../components/SliderData'
export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <Hero heading="Next App" message="This is a next app "/>
     <Slider slides={SliderData}/>
 
    </div>
  )
}
